### ISSUE TITLE
'NewRelicGQL' object has no attribute 'get_linked_account_by_name'

### ISSUE THREAD

**Issue by kdomagal** [newrelic/newrelic-lambda-cli#151]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When running basic installation command I'm getting an exception about missing method.

## Steps to Reproduce

Try to install new integration:
`newrelic-lambda integrations install --nr-account-id <id> --nr-api-key <key>`

## Expected Behaviour

Should install the integration.

## Relevant Logs / Console output

```
Validating New Relic credentials
Retrieving integration license key
Checking for a pre-existing link between New Relic and AWS
Traceback (most recent call last):
  File "/usr/local/bin/newrelic-lambda", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.7/site-packages/newrelic_lambda_cli/utils.py", line 27, in _boto_error_wrapper
    return func(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/newrelic_lambda_cli/cli/__init__.py", line 27, in main
    cli()
  File "/Library/Python/3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/3.7/site-packages/newrelic_lambda_cli/cli/integrations.py", line 132, in install
    integrations.validate_linked_account(gql_client, input)
  File "/Library/Python/3.7/site-packages/newrelic_lambda_cli/integrations.py", line 482, in validate_linked_account
    account = gql.get_linked_account_by_name(input.linked_account_name)
AttributeError: 'NewRelicGQL' object has no attribute 'get_linked_account_by_name'
```

## Your Environment

mac OS Catalina 10.15.7
python: Python 3.7.3

## Additional context

Seems like that method `get_linked_account_by_name` does not exist in `NewRelicGQL`.

**Comment by kolanos** [comment]
@kdomagal Thanks for reporting this issue. Working on a fix, should be included in `v0.5.4`.
